#Default Parameters
FRAMETYPE_DEFAULT         = 'normal'
EXPOSURE_TIME_DEFAULT     = 500
RBI_NUM_FLUSHES_DEFAULT   = 0
RBI_EXPOSURE_TIME_DEFAULT = 500
REPEAT_DELAY_DEFAULT      = 10

#Font Styles
FIELD_LABEL_FONT      = "Courier 10 normal"
HEADING_LABEL_FONT    = "Helvetica 14 bold"
SUBHEADING_LABEL_FONT = "Helvetica 10 bold"
